export default [
  {
    AdvCode: "CCC-DDSC-02",
    AdvName: "A Fool and His Gold",
    Date: "March 2, 2022",
    Time: "00:30 AM",
    Duration: "4 hours",
    CurrentPlayers: "5",
    MaxPlayers: "6",
    WaitlistCount: "0",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "Clark",
    Warnings: "Animal Cruelty",
  },
  {
    AdvCode: "DDAL00-02E",
    AdvName: "Forgotten Foes",
    Date: "March 3, 2022",
    Time: "09:10 AM",
    Duration: "3 hours",
    CurrentPlayers: "6",
    MaxPlayers: "6",
    WaitlistCount: "1",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "Griffmeister",
    Warnings:
      "Loads of combar and exploration. Minimal RP. 3hour max with hard cut off if not complete.",
  },
  {
    AdvCode: "DDAL-DRW-12",
    AdvName: "To Walk the Cold Dark",
    Date: "March 3, 2022",
    Time: "01:00 AM",
    Duration: "4 hours",
    CurrentPlayers: "4",
    MaxPlayers: "6",
    WaitlistCount: "0",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "Johnny",
    Warnings:
      "death (murder by consuming flesh), “madness,” abduction, imprisonment, illness, loss of self.",
  },
  {
    AdvCode: "CCC-004",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-005",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-006",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-007",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-008",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-009",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-010",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-011",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-012",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
  {
    AdvCode: "CCC-013",
    AdvName: "Adventure Name",
    Date: "Date:D",
    Time: "Time:t",
    Duration: "# hours",
    CurrentPlayers: "X",
    MaxPlayers: "Y",
    WaitlistCount: "Z",
    DescriptionFull:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos, a minima ullam veritatis sed vero consequuntur animi velit consequatur voluptatem recusandae accusantium ratione sunt? Odio, ab earum? Neque, natus ab.",
    DM: "DM Alias",
    Warnings: "Any content / trigger warnings.",
  },
];
